### ISSUE TITLE
eval和test的速度很慢，这种情况正常吗

### ISSUE THREAD

**Issue by ZhangIceNight** [chaitjo/geometric-rna-design#11]
作者你好，
请问我在复现实验的时候，出现了eval 和 test的时间很长的现象，这是正常情况吗？
![image](https://github.com/chaitjo/geometric-rna-design/assets/51945786/c14601bf-ccf0-4b9f-918d-cb81ece6ed41)

因为数据集和原始数据集有了一些更新，导致出现了很多新的数据（这些数据中有部分的 sec_struc中 左括号数量多于右括号，导致计算对应的adj的时候报错），于是我对原始的代码做了如下修改，将计算过程放到了try里面，如果是错误的就跳出：

`def dotbracket_to_adjacency(sec_struct: str) -> np.ndarray:
    """
    Convert secondary structure in dot-bracket notation to 
    adjacency matrix.
    """
    n = len(sec_struct)
    adj = np.zeros((n, n), dtype=np.int8)
    stack = []
    empty_count = 0
    for i, db_char in enumerate(sec_struct):
        if db_char == '(':
            stack.append(i)
        elif db_char == ')':
            try:
                j = stack.pop()
                adj[i, j] = 1
                adj[j, i] = 1
            except IndexError:
                break
    return adj`

其他地方都没有改变

大概eval 和 test 每个都要接近8小时，查看占用，发现gpu长时间不用，一直是cpu在跑一个叫做contrafold的进程，希望大佬解惑。

**Comment by chaitjo** [comment]
Hello, thanks for your interest. Is it possible to write your issue in English? I am not a speaker of Mandarin.

I translated the title:
> eval and test are very slow. Is this normal?

No, the speeds you are observing are not normal. Things should be much faster, even on CPU. And it looks like there may be an issue with how you are using EternaFold (this is what uses contrafold.cpp in the background).

**Comment by ZhangIceNight** [comment]
``> Hello, thanks for your interest. Is it possible to write your issue in English? I am not a speaker of Mandarin.
> 
> I translated the title:
> 
> > eval and test are very slow. Is this normal?
> 
> No, the speeds you are observing are not normal. Things should be much faster, even on CPU. And it looks like there may be an issue with how you are using EternaFold (this is what uses contrafold.cpp in the background).

Thank you so much for your reply.

（1）
I haven't modified any code related to EternaFold, just follow the code that was already written in the repository.

The only thing I modified is :

Since the dataset  have been updated, resulting in many new data points (among which some have more left parentheses than right parentheses in `sec_struc`, causing errors when use function 'dotbracket_to_adjacency'), so I made the following modification to the original code. I placed the calculation process inside a `try` block, and if there's an error, it returns a zero array. Could this slow performance be caused by the operation I performed?

```
def dotbracket_to_adjacency(sec_struct: str) -> np.ndarray:
    """
    Convert secondary structure in dot-bracket notation to 
    adjacency matrix.
    """
    n = len(sec_struct)
    adj = np.zeros((n, n), dtype=np.int8)
    stack = []
    empty_count = 0
    for i, db_char in enumerate(sec_struct):
        if db_char == '(':
            stack.append(i)
        elif db_char == ')':
            try:
                j = stack.pop()
                adj[i, j] = 1
                adj[j, i] = 1
            except IndexError:
                break
    return adj
```

（2）
In addition, I'm sorry I'm not familiar with C++, so I would like to ask: does the `c.cpp` in the project execute locally, or does it call an interface to execute on their website?
（3）
Since there are error files, I tried to filter out those erroneous data directly in the `process_data.py`. However, I noticed that the existing split files `${split_type}_split.pt` from the repository were used when dividing the training and test sets. How should I divide this new dataset? Is there any ready-made code available?

Thank you again for your help!

**Comment by chaitjo** [comment]
> Since the dataset have been updated, resulting in many new data points (among which some have more left parentheses than right parentheses in sec_struc, causing errors when use function 'dotbracket_to_adjacency'), so I made the following modification to the original code.

What do you mean by the dataset being updated? Do you mean that you are using a different/new/custom dataset?

> among which some have more left parentheses than right parentheses in sec_struc

This should actually **never** happen b/c it would mean that something is wrong with how the secondary structure is being computed from the input PDB file(s). Can you perhaps show me what the secondary structure looks like? (See here for the dot-bracket notation: https://eternagame.fandom.com/wiki/Dot-Bracket_Notation)

**Comment by chaitjo** [comment]
I recently updated the instructions for preparing the data and for reproducing our splits for benchmarking: https://github.com/chaitjo/geometric-rna-design/pull/16

Somebody else told me that RNAsolo was no longer allowing downloading older versions based on date cutoffs, and I suspect the issues you were facing can be due to the same reason. If you try the new data instructions in the README, I think it should work. 

Let me know how it goes!
