### ISSUE TITLE
Where is RibonanzaNet?

### ISSUE THREAD

**Issue by RichardChangCA** [chaitjo/geometric-rna-design#12]
Hello,

Thanks for your paper and open source codes. Currently I am working on the implementation of your codes. I found one problem which is missing from tools.ribonanzanet.network import RibonanzaNet in notebooks/design.ipynb. How can I solve this issue?

Thanks in advance!

Best,

**Comment by RichardChangCA** [comment]
I guess this Ribonanzanet is inside rna-inverse-folding folder, but where is it?

**Comment by chaitjo** [comment]
Hi @RichardChangCA many thanks for your interest!

I still need to push code for my RibonanzaNet API (you can search for the original codebase by Shujun He), thanks for catching that. RibonanzaNet was used as another computational evaluation tool in addition to EternaFold (same idea of forward prediction for designed sequences). 

At present, you can also comment out the lines that use RibonanzaNet to run the code. 

I will ping you asap when I add RibonanzaNet.

**Comment by chaitjo** [comment]
Hi @RichardChangCA, the latest release of the codebase should include all the code for RibonanzaNet now. You can use RibonanzaNet as part of the Design notebook as an additional self-consistency scorer (albeit we have found 2D and 3D self-consistency scores to actually be more informative than this one).
