### ISSUE TITLE
where is cluster.txt?

### ISSUE THREAD

**Issue by dark-flash** [chaitjo/geometric-rna-design#17]
Your work is very impressive, and i want to process data by your instructions. But when i run process_data.py, i met the error like this:

Traceback (most recent call last):
  File "/cpfs01/projects-HDD/cfff-282dafecea22_HDD/cfff_siqi/RNA/geometric-rna-design/data/process_data.py", line 230, in <module>
    cluster_list_structsim = cluster_structure_similarity(
  File "/cpfs01/projects-HDD/cfff-282dafecea22_HDD/cfff_siqi/RNA/geometric-rna-design/data/../src/data/clustering_utils.py", line 148, in cluster_structure_similarity
    clustered_structures = run_qtmclust(
  File "/cpfs01/projects-HDD/cfff-282dafecea22_HDD/cfff_siqi/RNA/geometric-rna-design/data/../src/data/clustering_utils.py", line 116, in run_qtmclust
    output_clusters = parse_qtmclust_cluster_file(output_cluster_filepath)
  File "/cpfs01/projects-HDD/cfff-282dafecea22_HDD/cfff_siqi/RNA/geometric-rna-design/data/../src/data/clustering_utils.py", line 76, in parse_qtmclust_cluster_file
    with open(file_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'cluster.txt'

I searched the ./data folder carefully, but can't find this 'cluster.txt' file. I wondered if this file missed in this repo or any other errors? I'm looking forward to your answer, thanks!

**Comment by chaitjo** [comment]
Hi @dark-flash, thanks for having a look at our work! 

I think that file is actually ** created ** once you run QTMclust on your PDB files. It is essentially a mapping of PDB ids that are judged to be in the same structural cluster.

I think that maybe there's a small bug with the filepaths which hopefully can be fixed.

Can you try and check on your end that the clustering actually did run successfully? (B/c this line: https://github.com/chaitjo/geometric-rna-design/blob/main/src/data/clustering_utils.py#L116  is only called ** after ** clustering is already done. It is only reading the contents of the clustered file and outputing it back to you. So I am guessing that in your case the clustering did happen but that the location of the output file was wrong.)

Perhaps past your full output log if possible?

**Comment by chaitjo** [comment]
PS. Sorry for the very late reply -- I missed seeing this issue pop up as I was moving countries.

**Comment by liyewen521** [comment]
First, thanks for your great work! 

I also encountered this issue. I think the reason is the wrong QTMclust path. 


The default qTMclust path is `~/USalign/qTMclust`, but the actual path is `~/geometric-rna-design/tools/USalign/qTMclust`
```python
def cluster_structure_similarity(
        input_pdb_files, 
        similarity_threshold: float = 0.45,
        chain_list_filepath: str = "chain_list",
        output_cluster_filepath: str = "cluster.txt",
        chain_dir: str = os.path.join(DATA_PATH, "raw"),
        qtmclust_exec_path: str = "~/USalign/qTMclust",
    ):
```

So I fixed this error by input error by giving the qTMclust path in `process_data.py`:

```python
    cluster_list_structsim = cluster_structure_similarity(
        [os.path.join(DATA_PATH, "raw", data["id_list"][0]+".pdb") for data in seq_to_data.values()],
        similarity_threshold = 0.45,
        qtmclust_exec_path = QTMCLUST_PATH
    )
```

Is this the correct way to fix it?
