### ISSUE TITLE
Ask for checkpoints

### ISSUE THREAD

**Issue by GRAPH-0** [chaitjo/geometric-rna-design#2]
Hi @chaitjo,

Thanks for your great work first!
Could you provide a pretrained checkpoint to run inference directly?

Best regards,
Han

**Comment by chaitjo** [comment]
Hello Han,

Thank you for your interest and sorry for my late response! The code + paper is still under active development so we haven't released a pretrained checkpoint yet. I expect that the model classes may change further as we improve things about the work and do more experiments.

We definitely plan to do this in the coming months once I am back from internship.

Best,
Chaitanya

**Comment by GRAPH-0** [comment]
Thanks for your reply and look forward to your subsequent releases!

**Comment by chaitjo** [comment]
Hi @GRAPH-0, I release that this is much delayed, but do have a look at the latest release of the codebase. You will find:
- A detailed tutorial on how to use gRNAde: https://github.com/chaitjo/geometric-rna-design/blob/main/tutorial/tutorial.ipynb
- gRNAde models accessable via command line: https://github.com/chaitjo/geometric-rna-design/blob/main/gRNAde.py
- Checkpoints: https://github.com/chaitjo/geometric-rna-design/tree/main/checkpoints 

Let me know if you have any questions!
