### ISSUE TITLE
Splits for benchmark

### ISSUE THREAD

**Issue by ParthBibekar** [chaitjo/geometric-rna-design#9]
Hi,

Congrats on the great work. As I understand `data/seqid_split.pt`  `data/das_split.pt` and `data/structsim_split.pt` contains the train, test, validation `idx` for different splits. And the corresponding `pdbid_<chain>` for those can be extracted from `processed_df.csv`. Can you provide this preprocessed `processed_df.csv` file or directly the PDB ids for easier access?

Thanks!

**Comment by chaitjo** [comment]
Hi @ParthBibekar, thanks for your interest! You can download exactly that via the links in the README: https://github.com/chaitjo/geometric-rna-design?tab=readme-ov-file#downloading-data

**Comment by ParthBibekar** [comment]
Thanks @chaitjo exactly what I needed!

**Comment by chaitjo** [comment]
Let me know if you need any other help setting this up :)
